/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sudoku_song_sudoku_FirstActivity */

#ifndef _Included_com_sudoku_song_sudoku_FirstActivity
#define _Included_com_sudoku_song_sudoku_FirstActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sudoku_song_sudoku_FirstActivity
 * Method:    getSudoString_jni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sudoku_song_sudoku_FirstActivity_getSudoString_1jni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
